steps:
- name: node:14.15.1
  entrypoint: npm
  args: ["install"]
  dir: 'vue'
- name: node:14.15.1
  entrypoint: npm
  args: ["run", "build"]
  dir: 'vue'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: 'vue'
timeout: "1600s"